<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            //     MEDICAL CENTER CHIEF (PINAKA-PARENT)
            ['employee_number'=>'RMBGH-0132527','prefix'=> 'DR', 'first_name'=>'Dave Anthony','middle_name'=>'Alico','last_name'=>'Vergara','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],         
            //     COMMITTEE (MEDICAL CENTER CHIEF CHILD's)
            ['employee_number'=>'RMBGH-0111538','prefix'=> 'DR', 'first_name'=>'Maria Rosela','middle_name'=>'Buenaventura','last_name'=>'Espinar','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0133434','prefix'=> 'DR', 'first_name'=>'Leah','middle_name'=>'Faderon','last_name'=>'Fajutagana','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'VACANT-0000001','prefix'=> null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // --VACANT
            //     HOSPITAL DIRECTOR (MEDICAL CENTER CHIEF 2ND CHILD)
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0133396','prefix'=> 'DR', 'first_name'=>'Raymond Rae','middle_name'=>'Regala','last_name'=>'Castañeda','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0133566','prefix'=> 'DR', 'first_name'=>'Mario Victor','middle_name'=>'Manoto','last_name'=>'Villardo','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], //  MEDICAL DIRECTOR (HOSPITAL DIRECTOR CHILD's)
            ['employee_number'=>'RMBGH-0000001','prefix'=> 'DIR', 'first_name'=>'Bradford Antonio','middle_name'=>'B','last_name'=>'Martinez','suffix'=>null, 'title'=>'dba', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HOSPITAL ADMINISTRATION DIVISION (HOSPITAL DIRECTOR CHILD's)
            ['employee_number'=>'RMBGH-0000002','prefix'=> 'DIR', 'first_name'=>'Pia Angelina','middle_name'=>'C','last_name'=>'Tan','suffix'=>null, 'title'=>'CPA', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], //  FINANCE DIRECTOR (HOSPITAL DIRECTOR CHILD's)
            ['employee_number'=>'RMBGH-0000003','prefix'=> 'DIR', 'first_name'=>'Neil','middle_name'=>'Gaddi','last_name'=>'Cabbo','suffix'=>null, 'title'=>'MAN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], //  NURSING DIRECTOR (HOSPITAL DIRECTOR CHILD's)
            //     MEDICAL DIRECTOR (CHILD's) ↓
            //     MEDICAL DIRECTOR ASSISTANT / DEPARTMENT's ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111058','prefix'=> 'DR', 'first_name'=>'Clodoaido','middle_name'=>'Magpantay','last_name'=>'Caringal','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0142875','prefix'=> 'DR', 'first_name'=>'Rashida Cawiya','middle_name'=>'Catipon','last_name'=>'Guiling-Decena','suffix'=>'MD', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111589','prefix'=> 'DR', 'first_name'=>'Jocelyn','middle_name'=>'Quinto','last_name'=>'Gacasan','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     HOSPITAL ADMINISTRATION DIVISION (CHILD's) ↓
            //     HOSPITAL ADMINISTRATION DEPARTMENT's HEAD's ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111155','prefix'=> null, 'first_name'=>'Marc Napoleon','middle_name'=>'Aquino','last_name'=>'Quiaoit','suffix'=>'III', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0000004','prefix'=> null, 'first_name'=>'Ruel','middle_name'=>'Velasco','last_name'=>'Subaran','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0121991','prefix'=> null, 'first_name'=>'Cristela','middle_name'=>'Veñegas','last_name'=>'Veñegas','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AGAIN BUT IN OTHER DEPARTMENT 
            ['employee_number'=>'RMBGH-0129968','prefix'=> null, 'first_name'=>'Uziel','middle_name'=>'Avellaneda','last_name'=>'Rutaquio','suffix'=>null, 'title'=>'RSW', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     FINANCE DIRECTOR (CHILD's) ↓
            //     PIA ANGELINA C. TAN, CPA (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD ↓
            ['employee_number'=>'RMBGH-0142883','prefix'=> null, 'first_name'=>'Ronilo','middle_name'=>'Mogol','last_name'=>'Jose','suffix'=>null, 'title'=>'CPA', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111597','prefix'=> null, 'first_name'=>'Maria Ruth','middle_name'=>'See','last_name'=>'Galut','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0142867','prefix'=> null, 'first_name'=>'Judith Fatima','middle_name'=>'Estabillo','last_name'=>'Garcia','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0000005','prefix'=> null, 'first_name'=>'Donnary','middle_name'=>'A','last_name'=>'Gavan','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111457','prefix'=> null, 'first_name'=>'Marion May','middle_name'=>'Meneses','last_name'=>'Cervera','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     NURSING DIRECTOR (CHILD's)
            //     NEIL G. CABBO, MAN (CHILD's)
            //     MA. VICARD TAGUBA ESTACIO AND LADY JANE GALO GAFFUD CARABBACAN IS PARENT. THEY ALL HAVE THEIR OWN CHILD ↓
            ['employee_number'=>'RMBGH-0111503','prefix'=> null, 'first_name'=>'Ma. Vicarl','middle_name'=>'Taguba','last_name'=>'Estacio','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0122734','prefix'=> null, 'first_name'=>'Lady Jane','middle_name'=>'Galo','last_name'=>'Gaffud-Carabbacan','suffix'=>null, 'title'=>'RN, MAN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     MEDICAL DIRECTOR (DIVISION) ↓
            //     CLODOAIDO M. CARINGAL, MD (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0093351','prefix'=> 'DR', 'first_name'=>'Sabina','middle_name'=>'Legaspi','last_name'=>'Mendoza','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0121991','prefix'=> 'DR', 'first_name'=>'Cristela','middle_name'=>'Veñegas','last_name'=>'Veñegas','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AGAIN
            ['employee_number'=>'RMBGH-0142778','prefix'=> 'DR', 'first_name'=>'Robert','middle_name'=>'Bernardo','last_name'=>'Belleza','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0000006','prefix'=> 'DR', 'first_name'=>'Joanne Raquel','middle_name'=>'Roque','last_name'=>'Teodoro','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'CS-0027341','prefix'=> 'DR', 'first_name'=>'Aina','middle_name'=>'Bautista','last_name'=>'Duque','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Consultant','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'CS-0042725','prefix'=> 'DR', 'first_name'=>'Adeluisa Mae','middle_name'=>'Rayel','last_name'=>'De Guzman-Besin','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Consultant','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'CS-0026258','prefix'=> 'DR', 'first_name'=>'Anna Samantha','middle_name'=>'Decastro','last_name'=>'Imperial','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Consultant','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111104','prefix'=> 'DR', 'first_name'=>'Mario Victor','middle_name'=>'Manoto','last_name'=>'Villardo','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HE IS THE MEDICAL DIRECTOR AND ALSO THE HEAD OF ANOTHER DEPARTMENT
            //     MEDICAL DIRECTOR (DIVISION) ↓
            //     Rashida Cawiya C. Guiling-Decena, MD (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0142875','prefix'=> 'DR', 'first_name'=>'Rashida Cawiya','middle_name'=>'Catipon','last_name'=>'Guiling-Decena','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0129976','prefix'=> 'DR', 'first_name'=>'Anna Liza','middle_name'=>'Campos','last_name'=>'Salita','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111023','prefix'=> 'DR', 'first_name'=>'Malaika','middle_name'=>'Laurente','last_name'=>'Salido-Ecalnir','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'VACANT-0000002','prefix'=> null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // --VACANT
            ['employee_number'=>'VACANT-0000003','prefix'=> null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // --VACANT
            ['employee_number'=>'RMBGH-0129941','prefix'=> 'DR', 'first_name'=>'Maria Isabel','middle_name'=>'Palma','last_name'=>'Rivera','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],  
            //     MEDICAL DIRECTOR (DIVISION) ↓
            //     JOCELYN Q. GACASAN, MD (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111589','prefix'=> 'DR', 'first_name'=>'Jocelyn','middle_name'=>'Quinto','last_name'=>'Gacasan','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AT HE'S OWN DEPARTMENT
            ['employee_number'=>'CS-0026103','prefix'=> 'DR', 'first_name'=>'Maria Angeline','middle_name'=>'De Leon','last_name'=>'Nicandro','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'RMBGH-0122793','prefix'=> null, 'first_name'=>'Maria Victoria','middle_name'=>'Rangas','last_name'=>'Santos','suffix'=>null, 'title'=>'RPH', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0133566','prefix'=> 'DR', 'first_name'=>'Mario Victor','middle_name'=>'','last_name'=>'Villardo','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AGAIN
            ['employee_number'=>'RMBGH-0133507','prefix'=> null, 'first_name'=>'Kate Lyn Anne','middle_name'=>'','last_name'=>'Salvador','suffix'=>null, 'title'=>'RRT', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Consultant','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111007','prefix'=> null, 'first_name'=>'Arnold Benedict','middle_name'=>'','last_name'=>'Yambao','suffix'=>null, 'title'=>'DMD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Consultant','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'CT-0037158','prefix'=> null, 'first_name'=>'Jenifer','middle_name'=>'','last_name'=>'Bagon','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'COS','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     HOSPITAL ADMINISTRATION DIVISION (DIVISION) ↓
            //     BRADFORD ANTONIO C. MARTINEZ, DBA (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111155','prefix'=>'ENGR', 'first_name'=>'Marc Napoleon','middle_name'=>'Aquino','last_name'=>'Quiaoit','suffix'=>'III', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0000004','prefix'=>null, 'first_name'=>'Ruel','middle_name'=>'Velasco','last_name'=>'Subaran','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'RMBGH-0122793','prefix'=> null, 'first_name'=>'Cristela','middle_name'=>'Veñegas','last_name'=>'Veñegas','suffix'=>null, 'title'=>'MD', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AGAIN
            ['employee_number'=>'RMBGH-0129968','prefix'=>null, 'first_name'=>'Uziel','middle_name'=>'Avellaneda','last_name'=>'Rutaquio','suffix'=>null, 'title'=>'RSW', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            //     HOSPITAL ADMINISTRATION DIVISION (DIVISION) ↓
            //     ENGR. MARC NAPOLEON A. QUIAOIT III (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0142905','prefix'=>'ENGR', 'first_name'=>'Joshua Anthony','middle_name'=>'Luzande','last_name'=>'Palaad','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'CT-0025794','prefix'=>'ENGR', 'first_name'=>'Cristopher','middle_name'=>'Poblete','last_name'=>'Española','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'COS','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'RMBGH-0111155','prefix'=> 'ENGR', 'first_name'=>'Marc Napoleon','middle_name'=>'Aquino','last_name'=>'Quiaoit','suffix'=>'III', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AT HE'S OWN DEPARTMENT
            ['employee_number'=>'RMBGH-0111082','prefix'=>null, 'first_name'=>'Cherry','middle_name'=>'Nilla','last_name'=>'Borja','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'CT-0008704','prefix'=>null, 'first_name'=>'Apolinario','middle_name'=>'Rosales','last_name'=>'Autor','suffix'=>'III', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'COS','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     HOSPITAL ADMINISTRATION DIVISION (DIVISION) ↓
            //     RUEL V. SUBARAN (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111295','prefix'=>null, 'first_name'=>'MA. Lourdes Teresa','middle_name'=>'Espinosa','last_name'=>'Jawili','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0143065','prefix'=>null, 'first_name'=>'Jan Bert','middle_name'=>'Isidoro','last_name'=>'Doquenia','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'RMBGH-0142816','prefix'=> null, 'first_name'=>'Julina','middle_name'=>'Nungay','last_name'=>'De Asis','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            //     HOSPITAL ADMINISTRATION DIVISION (DIVISION) ↓
            //     CRISTELA V. VEÑEGAS, MD (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0122122','prefix'=>null, 'first_name'=>'Naomi Noreen','middle_name'=>'Olivares','last_name'=>'Buenafe','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'VACANT-0000004','prefix'=>null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],  // ---VACANT
            ['employee_number'=>'RMBGH-0121991','prefix'=> null, 'first_name'=>'Cristela','middle_name'=>'Veñegas','last_name'=>'Veñegas','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            ['employee_number'=>'RMBGH-0075973','prefix'=>null, 'first_name'=>'Sharon Grace','middle_name'=>'Vicente','last_name'=>'Meneses','suffix'=>'MD', 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], 
            //     HOSPITAL ADMINISTRATION DIVISION (DIVISION) ↓
            //     UZIEL A. RUTAQUIO, RSW (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0129909','prefix'=>null, 'first_name'=>'MA. Cristina','middle_name'=>'De Leon','last_name'=>'Pacubas','suffix'=>null, 'title'=>'RSW', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0143065','prefix'=>null, 'first_name'=>'Teresita','middle_name'=>'Pagunsan','last_name'=>'Abrico','suffix'=>null, 'title'=>'RND', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],  // ---VACANT
            //     NURSING DIRECTOR (DIVISION) ↓
            //     MA. VICARL T. ESTACIO, RN (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0111503','prefix'=>null, 'first_name'=>'MA. Vicarl','middle_name'=>'Taguba','last_name'=>'Estacio','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()], // HEAD AT HE'S OWN DEPARTMENT
            ['employee_number'=>'CT-0031791','prefix'=>null, 'first_name'=>'Kimberly Beth Ponce','middle_name'=>'De Leon','last_name'=>'Kampton','suffix'=>null, 'title'=>'RN, MAN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'COS','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     NURSING DIRECTOR (DIVISION) ↓
            //     LADY JANE G. GAFFUD-CARABBACAN, RN, MAN (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'VACANT-0000005','prefix'=>null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'VACANT-0000006','prefix'=>null, 'first_name'=>'VACANT','middle_name'=>null,'last_name'=>'VACANT','suffix'=>null, 'title'=>null, 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            //     NURSING DIRECTOR (DIVISION) ↓
            //     MA. VICARL T. ESTACIO, RN & LADY JANE G. GAFFUD-CARABBACAN, RN, MAN (CHILD's) ↓
            //     THIS IS ALL PARENTS. THEY ALL HAVE THEIR OWN CHILD AND DEPARTMENT ↓
            ['employee_number'=>'RMBGH-0122769','prefix'=>null, 'first_name'=>'Marijane','middle_name'=>'Abella','last_name'=>'Lagño','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0122742','prefix'=>null, 'first_name'=>'Connie Ann','middle_name'=>'Hagoriles','last_name'=>'Silva','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111922','prefix'=>null, 'first_name'=>'Herminio','middle_name'=>'Espiritu','last_name'=>'Sarmiento','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111422','prefix'=>null, 'first_name'=>'Noreen Eunice','middle_name'=>'Cabanding','last_name'=>'Cruz','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0083984','prefix'=>null, 'first_name'=>'Ranee','middle_name'=>'Gutierrez','last_name'=>'Sangalang','suffix'=>null, 'title'=>'RM, RN, MAN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ['employee_number'=>'RMBGH-0111287','prefix'=>null, 'first_name'=>'Darwin','middle_name'=>'Olaya','last_name'=>'Leonardo','suffix'=>null, 'title'=>'RN', 'sex'=>null,'birthdate'=>null,'civil_status'=>null,'blood_type'=>null,'citizenship'=>'Filipino','email'=>null,'contact_no'=>null,'region'=>null,'city'=>null,'barangay'=>null,'zipcode'=>null,'employment_type'=>'Plantilla','employment_status'=>'Active','created_at'=>now(),'updated_at'=>now()],
            ];

        foreach ($employees as $e) {
            Employee::updateOrCreate(
                ['employee_number' => $e['employee_number']],
                [
                    // ✅ only columns that exist in employees migration
                    'prefix' => $e['prefix'] ?? null,
                    'first_name' => $e['first_name'],
                    'middle_name' => $e['middle_name'] ?? null,
                    'last_name' => $e['last_name'],
                    'suffix' => $e['suffix'] ?? null,

                    'title' => $e['title'] ?? null,
                    'position_designation' => $e['position_designation'] ?? null,

                    'role' => $e['role'] ?? null,
                    'employment_type' => $e['employment_type'] ?? null,
                    'employment_status' => $e['employment_status'] ?? null,

                    // optional defaults
                    'aligned' => $e['aligned'] ?? false,
                    'expanded' => $e['expanded'] ?? false,
                    'notes' => $e['notes'] ?? null,

                    // if you will set later:
                    'plantilla_item_id' => $e['plantilla_item_id'] ?? null,
                    'sg_level' => $e['sg_level'] ?? null,
                    'step_increment_id' => $e['step_increment_id'] ?? null,
                ]
            );
        }
    }
}