<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $employees = [

            ['RMBGH-0132527','Chief',null,null,'DR','Dave Anthony','Alico','Vergara',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111538','Chairman, Public Health Unit',null,null,'DR','Maria Rosela','Buenaventura','Espinar',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133434','Head, Quality, Risk Management, & Regulation Compliance Office',null,null,'DR','Leah','Faderon','Fajutagana',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133396','Hospital Director',null,null,'DR','Raymond Rae','Regala','Castañeda',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133566','Medical Director',null,null,'DR','Mario Victor','Manoto','Villardo',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000003','Chief, Hospital Administration Division',null,null,'DIR','Bradford Antonio','B','Martinez',null,'DBA',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000004','Finance Director',null,null,null,'Pia Angelina','C','Tan',null,'CPA',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000005','Nursing Director',null,null,null,'Neil','Gaddi','Cabbo',null,'MAN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111724','Staff',null,null,null,'Rutchel','Andaya','Abanto',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122688','Staff',null,null,null,'Victor','Velarde','Abapo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111104','Staff',null,null,null,'Marissa Anne','De Jesus','Abellar',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111708','Head, Dietary',null,null,null,'Teresita','Pagunsan','Abrico',null,'RND',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137022','Staff',null,null,null,'Novy-Ann','Navera','Abrigo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133353','Staff',null,null,null,'Ralph','Jerez','Acosta',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142964','Staff',null,null,null,'Sheila','Patlingrao','Adorable',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142972','Staff',null,null,null,'Mark Anthony','Nicolas','Aggabao',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0110965','Staff',null,null,null,'Maria Charmaigne','Gabriel','Agtang',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137049','Staff',null,null,null,'Louren Angelica','Concepcion','Agunod',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137057','Staff',null,null,null,'Glenda','Jose','Alison',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111694','Staff',null,null,null,'Gaspar','Valois','Ambita',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133361','Staff',null,null,null,'Genelyn','Balbiran','Aquino',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143871','Staff',null,null,null,'Angeline','Buenaflor','Arellano',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129666','Staff',null,null,null,'Jonel','Garcia','Balabbo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111686','Staff',null,null,null,'Mariliza','Paraggua','Balabbo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142999','Staff',null,null,null,'Josephine','Musenabre','Balao-Baclagan',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137065','Staff',null,null,null,'Judith','Caridad','Baldemor',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111678','Staff',null,null,null,'Princess Coleen','Book','Baloloy',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129674','Staff',null,null,null,'Krisha','Llerena','Baluyut',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137073','Staff',null,null,null,'Maria Maycel',null,'Banado',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129682','Staff',null,null,null,'Hannah Grace','Butel','Baquiran-Lat',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133388','Staff',null,null,null,'Rey Christian','Ampayo','Barbosa',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129704','Staff',null,null,null,'Christina Joyce','Cabiluna','Bastida',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143006','Staff',null,null,null,'Mary Gail','Flores','Baybayan',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143014','Staff',null,null,null,'Charyll Maevelyn','Tribaco','Baylon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129712','Staff',null,null,null,'Rj','Balaobao','Beatingo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142778','Head, Family Medicine',null,null,'DR','Robert','Bernardo','Belleza',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0110973','Staff',null,null,null,'Allan','Caraos','Belo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111384','Staff',null,null,null,'Tisha Jane','De Guzman','Benitez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142786','Staff',null,null,null,'David','Tuazon','Boque',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111082','Officer-In-Charge, Linen/HouseKeeping',null,null,null,'Cherry','Nilla','Borja',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129739','Staff',null,null,null,'Marichu','Abela','Brillantes',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137081','Staff',null,null,null,'Cristy Jane','Cueto','Bugarin',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111643','Staff',null,null,null,'Crispina','Ocrisma','Bulanadi',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111651','Staff',null,null,null,'Marlon Jr.','Tesorero','Bulatao','Jr',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143898','Staff',null,null,null,'Genara Valerie','Aydinan','Bumad-Ong',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111635','Staff',null,null,null,'Rusty','Lopez','Cabangon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142794','Staff',null,null,null,'Berna-Lor Nica','Velarde','Cabillar',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0121959','Staff',null,null,null,'Hedelita','Redondo','Cabotage',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111619','Staff',null,null,null,'Catherine','Sandoy','Cabotaje',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122696','Staff',null,null,null,'Rosen Lord','Hernandez','Cabrera',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143901','Staff',null,null,null,'Lea Anne','Iranga','Cacanindin',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142808','Staff',null,null,null,'Mark Anthony','Reoma','Campo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137103','Staff',null,null,null,'Cindy','Lapez','Candaroma',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111473','Staff',null,null,null,'Darwin','Cañega','Canonce',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111058','Assistant Director for Medical Services',null,null,'DR','Clodoaido','Magpantay','Caringal',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111465','Staff',null,null,null,'Annalyka','Andrada','Carullo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143928','Staff',null,null,null,'Mark Alvin','Onal','Catedral',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0121967','Staff',null,null,null,'Dexter John','Tumaneng','Catiwa',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143022','Staff',null,null,null,'Jonalyn','Rivera','Cattian',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111481','Staff',null,null,null,'Anita','Jaime','Cecillano',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111945','Staff',null,null,null,'Carmen','Celestial','Cellona',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143049','Staff',null,null,null,'Estella','Capili','Cenia',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111457','Head, Cash Management',null,null,null,'Marion May','Meneses','Cervera',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137111','Staff',null,null,null,'Maria Theresa','Figueroa','Cezar',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129747','Staff',null,null,null,'Jennifer','Manlutac','Cheng',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133418','Staff',null,null,null,'Albert Ryan','Javellana','Chua',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143936','Staff',null,null,null,'Joey','Asperin','Cordero',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111449','Staff',null,null,null,'Mercy','Montuya','Cruz',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111422','Special Care Department Supervisor',null,null,null,'Noreen Eunice','Cabanding','Cruz',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137138','Staff',null,null,null,'Charity','Balabbo','Cuntapay',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111392','Staff',null,null,null,'Purita','David','Dantes',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111406','Staff',null,null,null,'Rodolfo','Nisola','David','Jr',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142816','Officer-In-Charge, Admitting Section',null,null,null,'Julina','Nungay','De Asis',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129755','Staff',null,null,null,'Albert','Mendoza','De Jesus',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122718','Staff',null,null,null,'Felipe','Dellosa','De Jesus','Jr',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129771','Staff',null,null,null,'Lolita','Santos','De Rueda',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137146','Staff',null,null,null,'Willy','Hermo','De Vera',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111031','Staff',null,null,null,'Patrick John','Biglang-Awa','Del Rosario',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111368','Staff',null,null,null,'Jeffry','Sales','Dela Cruz',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143057','Staff',null,null,null,'Jhesel','Quezada','Dela Cruz',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129763','Staff',null,null,null,'Jimmy','Sales','Dela Cruz','Jr',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143944','Staff',null,null,null,'Reymark','Raoet','Dela Cruz',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142824','Staff',null,null,null,'Jason','Torres','Delos Santos',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143952','Staff',null,null,null,'Imelda','Visda','Didulo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143065','Officer-In-Charge, Information Technology Department',null,null,null,'Jan Bert','Isidoro','Doquenia',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111341','Staff',null,null,null,'Lloyd','Gatmaitan','Doremon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143979','Staff',null,null,null,'Virgie','Edejer','Edloy',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129798','Staff',null,null,null,'Arlene','Naval','Eguillon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111511','Staff',null,null,null,'Ronwaldo','Domingo','Emerenciana',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122726','Staff',null,null,null,'Jasmine','San Jose','Escosa',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111503','Assistant of Nursing Director for Patient Services/Division Secretary',null,null,null,'Ma. Vicarl','Taguba','Estacio',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133426','Staff',null,null,null,'Chiqui','Uno','Esteban',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142832','Staff',null,null,null,'Vanessa Mae','Pagba','Estidola',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111546','Staff',null,null,null,'Armida','Evangelista','Estrada',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142859','Staff',null,null,null,'Luisa','Balajadia','Evangelista',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0110957','Staff',null,null,null,'Melbert','Recepcion','Evangelista',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111562','Staff',null,null,null,'Joanna Marie','Mencias','Fernandez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129801','Staff',null,null,null,'Jose Leonardo','Ramos','Gabriel',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111589','Assistant Director for Ancillary Services',null,null,'DR','Jocelyn','Quinto','Gacasan',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122734','Assistant of Nursing Director for Administration and Training',null,null,null,'Lady Jane','Galo','Gaffud',null,'RN, MAN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111597','Officer-In-Charge, Budget Department',null,null,null,'Maria Ruth','See','Galut',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143987','Staff',null,null,null,'Gwen','Publico','Gamet',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142867','Head, Billing and Claims',null,null,'DR','Judith Fatima','Estabillo','Garcia',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111333','Staff',null,null,null,'Jenilyn','Lopez','Guardian',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129828','Staff',null,null,null,'Rashida Sakia','Catipon','Guiling',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142875','Assistant Director for Surgical Services',null,null,'DR','Rashida Cawiya','Catipon','Guiling-Decena',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111317','Staff',null,null,null,'Dennis','Gomez','Gutierrez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143073','Staff',null,null,null,'Janet','Mabuan','Harion',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129836','Staff',null,null,null,'Brian Rainier','Talion','Herradura',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111309','Staff',null,null,null,'Carl Christian','Nebres','Hersano',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111295','Head, Medical Records',null,null,null,'Ma. Lourdes Teresa','Espinosa','Jawili',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129844','Staff',null,null,null,'Art','Evangelista','Jimenez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143995','Staff',null,null,null,'Ma. Janah Clarissa','Pecho','Jimenez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142883','Head, Finance Services',null,null,null,'Ronilo','Mogol','Jose',null,'CPA',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0144002','Staff',null,null,null,'Ritchie','De Gracia','Kilapio',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122769','Outpatient Department Supervisor',null,null,null,'Marijane','Abella','Lagno',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111287','Central Supply & Sterilization Department Supervisor',null,null,null,'Darwin','Olaya','Leonardo',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143081','Staff',null,null,null,'Maria Britannica','Abalo','Lingling',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0091731','Staff',null,null,null,'Regine Rose','Requiestas','Logrosa',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137154','Staff',null,null,null,'Gem Marie',null,'Loro',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111279','Staff',null,null,null,'Maria Kristina','Vallecruz','Macario',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133442','Staff',null,null,null,'Joana Marie','Callueng','Macayaon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111252','Staff',null,null,null,'Carlito','Leynes','Maliwanag',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0144029','Staff',null,null,null,'Aiza','Tumaliuan','Mallari',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143103','Staff',null,null,null,'Wendy Sairah','Santos','Mamansag',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0144037','Staff',null,null,null,'Paulo','Soledad','Mamiloto',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129852','Staff',null,null,null,'Reijen Ayessa','Cabo','Manansala',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142891','Staff',null,null,null,'Irene','Calingacion','Manso',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111244','Staff',null,null,null,'Elmer','Duene','Marfiga',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0144045','Staff',null,null,null,'Nathalie Mae','Vega','Martin-Vega',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129879','Staff',null,null,null,'Alona','Argenio','Medallo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143111','Staff',null,null,null,'Loraine','Sarmiento','Mendoza',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0093351','Head, Outpatient Department',null,null,'DR','Sabina','Legaspi','Mendoza',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0075973','Head, Customer Relations Management',null,null,'DR','Sharon Grace','Vicente','Meneses',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133469','Staff',null,null,null,'Angel','Altiche','Nielo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129887','Staff',null,null,null,'Rodolfo','Garcia','Ocera','Jr',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129895','Staff',null,null,null,'Ginalyn','Rubia','Oxales',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129909','Officer-In-Charge, Medical Social Service Department',null,null,null,'Ma. Cristina','De Leon','Pacubas',null,'RSW',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142905','Head, Property Management',null,null,'ENGR','Joshua Anthony','Luzande','Palaad',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133477','Staff',null,null,null,'Marcelino','Janoras','Palitic','III',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111171','Staff',null,null,null,'Luzviminda','Dayag','Pascual',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142913','Staff',null,null,null,'Maribel','Deocampo','Patlingrao',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111163','Staff',null,null,null,'Manuel','Gerna','Payad','III',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142921','Staff',null,null,null,'Ainy','Torcita','Pendon-Niogan',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133485','Staff',null,null,null,'Luzvi May','Buscaino','Quiaoit',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111155','Chief, Facility Management Dvision',null,null,'ENGR','Marc Napoleon','Aquino','Quiaoit','III',null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129917','Staff',null,null,null,'Carlo Jay','Borja','Ragas',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111759','Staff',null,null,null,'Christine','Villena','Ragas',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129925','Staff',null,null,null,'Marites','Rabe','Razonable',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122785','Staff',null,null,null,'Angelica','Basan','Remitera',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129933','Staff',null,null,null,'Juner','Entize','Reyes',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129941','Head, PACU',null,null,'DR','Maria Isabel','Palma','Rivera',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111147','Staff',null,null,null,'Maria Perlita','Laxina','Rivo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111139','Staff',null,null,null,'Corazon','Cerdan','Rodrigo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0029149','Staff',null,null,null,'Remedios','Ramirez','Romero',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111112','Staff',null,null,null,'Keithlyn','Sarmiento','Roxas',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137162','Staff',null,null,null,'Gremond','Tumanon','Rulloda',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129968','Head, Patient Care Support Services Cluster',null,null,null,'Uziel','Avellaneda','Rutaquio',null,'RSW',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133493','Staff',null,null,null,'Ailyn','Dengal','Sabroso',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111023','Head, Anesthesiology',null,null,'DR','Malaika','Laurente','Salido-Ecalnir',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129976','Head, Obstetrics & Gynecology',null,null,'DR','Anna Liza','Campos','Salita',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137189','Staff',null,null,null,'Jade','Labay','Salvador',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111929','Staff',null,null,null,'Luisito','Pineda','Salvador',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133507','Head, Pulmonary Unit',null,null,null,'Ma. Kate Lyn Anne','Libao','Salvador',null,'RRT',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111902','Staff',null,null,null,'Raquel','Ruales','Samson',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111899','Staff',null,null,null,'Gundelino','Dela Cruz','Sanchez',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0083984','General Nursing Department Supervisor',null,null,null,'Ranee','Gutierrez','Sangalang',null,'RM, RN, MAN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133515','Staff',null,null,null,'Jhoana Rose','Militante','Santisteban',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122793','Head, Pharmacy',null,null,null,'Maria Victoria','Rangas','Santos',null,'RPH',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137197','Staff',null,null,null,'Renz Joharra','Abalos','Santos',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111922','OR / DR Spervisor',null,null,null,'Herminio','Espiritu','Sarmiento',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111872','Staff',null,null,null,'Rommel','Dela Cruz','Siblang',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122807','Staff',null,null,null,'Jennelyn','Sunio','Silarde',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111864','Staff',null,null,null,'Marie Joy','Bermas','Sillon',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122742','Emergency Room Supervisor',null,null,null,'Connie Ann','Hagoriles','Silva',null,'RN',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111856','Staff',null,null,null,'Stephanie','Aquino','Sombillo',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129984','Staff',null,null,null,'Ronello','Bernal','Sulayao',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133523','Staff',null,null,null,'Kim','Silvestre','Tabilin',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0129992','Staff',null,null,null,'Louisse Kimberlyn','Papa','Taganile',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111821','Staff',null,null,null,'Christine Joy','Iguin','Tango',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143138','Staff',null,null,null,'Kristina','Parochilin','Tatad',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000001','head, Pediatrics',null,null,'DR','Joanne Raquel','Roque','Teodoro',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111783','Staff',null,null,null,'Mark Lester','Saliba','Tesorero',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0121983','Staff',null,null,null,'Diana Marie','Torres','Tolentino',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0137219','Staff',null,null,null,'Renato','Inlajusta','Torregosa',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133531','Staff',null,null,null,'La Niña','Tagalogon','Ubal',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0143146','Staff',null,null,null,'Cecille','Jaen','Vajio',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133558','Staff',null,null,null,'Richard','Ines','Valino',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0121991','Head',null,null,'DR','Cristela','Veñegas','Veñegas',null,'MD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0144053','Staff',null,null,null,'Maureen','Watiwat','Villadolid',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111767','Staff',null,null,null,'Michael Benedict','Peregrino','Villamor',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0142948','Staff',null,null,null,'Lovelyn','Salo','Vilog',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0130001','Staff',null,null,null,'Jay-Pee','Ramos','Viloria',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0133574','Staff',null,null,null,'Glenn','Aquino','Vivas',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111732','Staff',null,null,null,'Eugene Timothy','Madamba','Wingsing',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-01431154','Staff',null,null,null,'John Kevin','Barcellano','Yalong',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0111007','Head, Dental Unit',null,null,null,'Arnold Benedict','Pascual','Yambao',null,'DMD',null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0122122','Officer-In-Charge, Human Resource Department',null,null,null,'Naomi Noreen','Olivares','Buenafe',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000007','Head, Procurement/Warehouse/Inventory',null,null,null,'Donnary','A','Gavan',null,null,null,'Plantilla','Active',null,'gray',1,1,null],
            ['RMBGH-0000006','Officer-In-Charge, Health Information Management Cluster',null,null,null,'Ruel','Velasco','Subaran',null,null,null,'Plantilla','Active',null,'gray',1,1,null],

            ['CS-0044287','Staff',null,null,null,'Arturo','Ayuyang','Bermejo','Jr',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042988','Staff',null,null,null,'Ianna Coreen','Ducusin','Abieras',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035876','Staff',null,null,null,'Lia Kathleen','Naurin','Abisana',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0033911','Staff',null,null,null,'Kathrina Rosario','Bautista','Agustin',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0028223','Staff',null,null,null,'Ana Kathrina','Punieg','Alas',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035265','Staff',null,null,null,'Nathaniel','Rendon','Alegre',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044114','Staff',null,null,null,'Predence Elwen','Mangahas','Almonte',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0031661','Staff',null,null,null,'Myra','Rios','Amon',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041403','Staff',null,null,null,'John Terence','Abes','Ampil',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043633','Staff',null,null,null,'Claire Dianne','Angeles','Andres',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036615','Staff',null,null,null,'Michael','Aseo','Arcellana',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043473','Staff',null,null,null,'Estalker','Galing','Argonza','III',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0034836','Staff',null,null,null,'Raphael Don','Dela Vega','Arias',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040248','Staff',null,null,null,'Jenniefer Kristine','Ico','Balingit',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036616','Staff',null,null,null,'Ernie','Guerina','Bautista','II',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0037006','Staff',null,null,null,'Janus Theodore','Poblete','Bernal',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042883','Staff',null,null,null,'Jannica Marie','Dialogo','Cabrera',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043477','Staff',null,null,null,'Stephanie Kaye','Asuncion','Cala',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044178','Staff',null,null,null,'Anna Nicola','Reyes','Calleja',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036619','Staff',null,null,null,'Angeli Joy','Cabanban','Caparas',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044031','Staff',null,null,null,'Maria Estela','Alano','Carandang',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0037512','Staff',null,null,null,'Kristine Lizette','Villar','Caringal',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043634','Staff',null,null,null,'Aida','Geli','Carriaga',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042934','Staff',null,null,null,'Mar Zandra Francine','Talamayan','Casil',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040372','Staff',null,null,null,'Jan Hermin','Ramos','Cataluña',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0034402','Staff',null,null,null,'Ma. Luisa','Alcantara','Crisostomo',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043474','Staff',null,null,null,'Marco',null,'Daniele',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026266','Staff',null,null,null,'Maria Caridad','Tan','De Castro',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044515','Staff',null,null,null,'Kathlene Elaine','Legaspi','De Guzman',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042725','Head, NICU',null,null,'DR','Adeluisa Mae','Rayel','De Guzman-Besin',null,'MD',null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041468','Staff',null,null,null,'Annaliza','Diamante','De Lara-Cruz',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042484','Staff',null,null,null,'Demetrio Romeo','Kabigting','Dela Cruz',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0023791','Staff',null,null,null,'Katherine','Figueroa','Dela Cruz',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043478','Staff',null,null,null,'Mustapha','Macapangkat','Derico','JR',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0027338','Staff',null,null,null,'Rei Paolo','Layon','Diaz',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0029540','Staff',null,null,null,'Rizza','Rosende','Diaz',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042200','Staff',null,null,null,'Erro','Tejoso','Diokno',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042984','Staff',null,null,null,'Dianne Ivy','Sesante','Ditangco',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0027340','Staff',null,null,null,'Angelito','Deri','Divina',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040250','Staff',null,null,null,'Jamielou','De Jesus','Dizon',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0027341','Head, Hemodialysis',null,null,'DR','Aina','Bautista','Duque',null,'MD',null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041320','Staff',null,null,null,'Maria Cristina','Pestaño','Ebora',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041321','Staff',null,null,null,'Engelbert','Cruz','Ednacot',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042935','Staff',null,null,null,'Marquiel','Santos','Esguerra',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043479','Staff',null,null,null,'Nescil Claire','Santos','Estandian',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042685','Staff',null,null,null,'Ma. Pamela Rica','Morales','Fajardo',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035196','Staff',null,null,null,'Paul Rey','Morales','Fajardo',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043480','Staff',null,null,null,'Jessica Catherine','Cabrera','Feria',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043475','Staff',null,null,null,'Jeane Jeanica','Florendo','Flores',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043481','Staff',null,null,null,'Gerald Vincent','Quiday','Fuentes',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041322','Staff',null,null,null,'Hannyline','Abas','Funtilar',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043482','Staff',null,null,null,'Faith Joan','Mesa','Gaerlan',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042983','Staff',null,null,null,'Abraham','Sayson','Garcia','JR',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043483','Staff',null,null,null,'Denise Lorraine','Desiderio','Guibani',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0032839','Staff',null,null,null,'Zesto','Ortega','Hernandez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043484','Staff',null,null,null,'Michelle Ann','Pacis','Ho',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043485','Staff',null,null,null,'Hans Gerard','Ang','Hui',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0029055','Staff',null,null,null,'Maria Angelica','Magat','Ibarra-Nisce',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042662','Staff',null,null,null,'Mark Joseph','Espina','Ignacio','II',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026258','Head, PICU',null,null,'DR','Anna Samantha','Decastro','Imperial',null,'MD',null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0034167','Staff',null,null,null,'Luren','Santos','Ingco',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042488','Staff',null,null,null,'Myrelle Frances','Federis','Isidoro',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043486','Staff',null,null,null,'Angela Marie','De Ocampo','Jimenez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0039335','Staff',null,null,null,'Catherine Marie','Gabriel','Jimenez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042967','Staff',null,null,null,'Regrine','Bolando','Lagarteja',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0037032','Staff',null,null,null,'Elbert John','Velasco','Layug',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044115','Staff',null,null,null,'Flordelis','Yazar','Lego',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0027347','Staff',null,null,null,'Jose Elvin','Rivera','Limjuico',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044516','Staff',null,null,null,'Carlo Alipio','Panganiban','Llido',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043476','Staff',null,null,null,'Roxanne','Adordionicio','Lobina',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026091','Staff',null,null,null,'Florence','Villorente','Los Baños',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042489','Staff',null,null,null,'Beverly Kaye','Cabrera','Macagba',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043487','Staff',null,null,null,'Katrina Marie','Reyes','Mamaril',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0037003','Staff',null,null,null,'Benson','Ng','Manda',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0029324','Staff',null,null,null,'Rachel','Alva','Maranan-Padlan',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0030204','Staff',null,null,null,'Clarina Fe','Mamaclay','Marcelino',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035055','Staff',null,null,null,'Mauricio','Foz','Marcelo','JR',null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036590','Staff',null,null,null,'Nikki Louise','Maglasang','Medina',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026103','Head, Radiology Department',null,null,'DR','Maria Angeline','De Leon','Nicandro',null,'MD',null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043489','Staff',null,null,null,'Donabel','Mejia','Ombao',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040168','Staff',null,null,null,'Mark Anthony','Rubio','Pablico',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036827','Staff',null,null,null,'Mary Anne','Marayag','Pandaraoan',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0032280','Staff',null,null,null,'Michael','Dimaano','Panganiban',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044512','Staff',null,null,null,'Ma. Patricia','Carreon','Papa',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044116','Staff',null,null,null,'Nikki Louise','Dela Cruz','Paquibot',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043490','Staff',null,null,null,'Art Cyril','Gallardo','Paredes',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0033870','Staff',null,null,null,'Rexee Rieh Mae','Lim','Pasagui',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043635','Staff',null,null,null,'Kathleen Jade','Bruno','Pascual',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0031530','Staff',null,null,null,'Ma. Tissa Carlamae','Villavert','Pasion',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043636','Staff',null,null,null,'Juan Roberto','Garcia','Patac',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044288','Staff',null,null,null,'Jan Paulo','Soriano','Pereira',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042492','Staff',null,null,null,'Franches Carla Marie','Marquez','Perez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042936','Staff',null,null,null,'Randolf','Andaya','Perez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040252','Staff',null,null,null,'Eunice Marie','Fulloso','Perez-Trajano',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043491','Staff',null,null,null,'Ana Margarita','Catolico','Pineda',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041411','Staff',null,null,null,'Aldrich Howell','Dy','Pua',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0000001','Staff',null,null,null,'Irene','Agresor','Ramos',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042663','Staff',null,null,null,'Michelle Ann','Gonzales','Ramos',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042079','Staff',null,null,null,'Francis Patrick','Mar','Realiza',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040253','Staff',null,null,null,'Rina','Rojas','Reyes',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040169','Staff',null,null,null,'Stephannie Angel','Magbitang','Ricafrente',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0038366','Staff',null,null,null,'John Carlos','Fernandez','Rimorin',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042686','Staff',null,null,null,'Wedney Rommel','Pinpin','Roncal',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035056','Staff',null,null,null,'Roland Gary','Cariño','Rosales',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0029543','Staff',null,null,null,'Aileen','Dorado','Roxas',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042938','Staff',null,null,null,'Maria Rhoma','Ramos','Rubio',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0037932','Staff',null,null,null,'Izrael Percy','Union','Sajise',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036187','Staff',null,null,null,'Ma. Loida','Ammugauan','Sajonas',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0035197','Staff',null,null,null,'Kareena Annette','Bayot','Salvador',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036592','Staff',null,null,null,'Miguel Jaime','Villalon','Salvador',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042493','Staff',null,null,null,'Ma. Corazon','Mendoza','Samson',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042080','Staff',null,null,null,'May Rachelle','Besas','Sanchez',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042970','Staff',null,null,null,'Richelle','De Luna','Santiago',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043492','Staff',null,null,null,'Jan Wayne','Reyes','Santiano',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041327','Staff',null,null,null,'Fatima Soraya','Timbayan','Santos',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042667','Staff',null,null,null,'Rochelle Anne','Ortega','Sevilla',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042335','Staff',null,null,null,'Bernadine Joy','Reyes','Soledad',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0041417','Staff',null,null,null,'King John Sherwin','Yee','Soon',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042939','Staff',null,null,null,'Johanne Myrrh','Enguito','Soriano',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0028455','Staff',null,null,null,'Margarett Grace','Esperat','Soriano',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044517','Staff',null,null,null,'Jeane Beatriz','Mendoza','Sta. Ana',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0036824','Staff',null,null,null,'Ryan Carlo','Bejer','Talosig',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0042495','Staff',null,null,null,'Liz Kringle','Vergara','Te',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0040172','Staff',null,null,null,'Lou Mervyn','Arguel','Tec',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0044117','Staff',null,null,null,'Blanchli Kane Arliss','Palaguittu','Teves',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043493','Staff',null,null,null,'Mark Leonard','Espiritu','Toledo',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0043494','Staff',null,null,null,'Sherica','Gomez','Torres',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026267','Staff',null,null,null,'Robert James','Sanchez','Valerio',null,null,null,'Consultant','Active',null,'gray',1,1,null],
            ['CS-0026249','Staff',null,null,null,'Ivy Marie','Magat','Viola-Cruz',null,null,null,'Consultant','Active',null,'gray',1,1,null],

            ['CT-0037181','Staff',null,null,null,'Ashley Christine','Sarmiento','Abulencia',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040142','Staff',null,null,null,'Karl Angelo','Viloria','Abuton',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044556','Staff',null,null,null,'Lyra','Garcia','Advincula',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040684','Staff',null,null,null,'Shaine Ro-An','Almoguera','Agana',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040676','Staff',null,null,null,'Aizza Czarina','Puyaoan','Aguila',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0029925','Staff',null,null,null,'Lucky Boy','Lapaz','Alabo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043302','Staff',null,null,null,'John Ric','Agbon','Alarcon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043640','Staff',null,null,null,'Jireh Cez','Villa','Alindogan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039188','Staff',null,null,null,'Aliana Cez','Cruz','Alipio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041395','Staff',null,null,null,'Clarance Keith','Rafal','Alipio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044518','Staff',null,null,null,'Jose Miguel','Daligdig','Almodovar',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036153','Staff',null,null,null,'Reyshell','Mirasol','Almonte',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039349','Staff',null,null,null,'Carmen','Said','Amado',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034777','Staff',null,null,null,'Shirly','Tambong','Amba',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042469','Staff',null,null,null,'Ma. Cristina','Capulong','Ancajas',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036810','Staff',null,null,null,'Cresel','Pescueso','Andawi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031073','Staff',null,null,null,'Michael','Caro','Andaya',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034325','Staff',null,null,null,'Jonalou','Coreg','Ando',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039352','Staff',null,null,null,'Cyndy','Peralta','Andres',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044519','Staff',null,null,null,'Kharen','Wandagan','Anggaco',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038191','Staff',null,null,null,'Reah Lynn Fatima','Marasigan','Antonio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041878','Staff',null,null,null,'Philline Therese','Paciencia','Aparis',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042962','Staff',null,null,null,'Harold','Tagulao','Aplacador',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042247','Staff',null,null,null,'Bryan','Daluz','Aquino',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042343','Staff',null,null,null,'Christine Hazel','Magarin','Aquino',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0029398','Staff',null,null,null,'John Dave','Savellano','Aragon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042963','Staff',null,null,null,'Josef Kevin','Gonzales','Arcilla',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040687','Staff',null,null,null,'Janielyn','Libores','Arevalo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0029060','Staff',null,null,null,'Cristina','Tiglao','Arzanan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038091','Staff',null,null,null,'Michelle','Ulep','Asuncion',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036605','Staff',null,null,null,'Michael Angelo','Yuson','Atienza',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0008704','Officer-In-Charge, Security',null,null,null,'Apolinario','Rosales','Autor',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033771','Staff',null,null,null,'Genalyn','Gacias','Bacani',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040143','Staff',null,null,null,'Jules Victor','Asuncion','Bacting',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041243','Staff',null,null,null,'Cherrie','Nalazon','Badilla',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037158','Head, Nutirion and Dietetics',null,null,null,'Jenifer','Canilao','Bagon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036820','Staff',null,null,null,'Sheika','Jai','Bairulla',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041555','Staff',null,null,null,'Arielle Ciara','Babay','Bajada',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043765','Staff',null,null,null,'Cloyd Leniel','Gonzales','Balajadia',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042468','Staff',null,null,null,'Exequiel','Balasi','Balabbo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040520','Staff',null,null,null,'Bernadette','Lambon','Balderama',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044272','Staff',null,null,null,'Alyza','Basnillo','Baldoz',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044557','Staff',null,null,null,'Ma. Antoinette','Pole','Baldoza',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041393','Staff',null,null,null,'Abiegail','Torres','Baliong',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037513','Staff',null,null,null,'Sherwin','Eleazar','Bangi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044520','Staff',null,null,null,'Angelica','Relato','Bapial',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042964','Staff',null,null,null,'Aaron Trezhkiel','Catangui','Barbarona',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037977','Staff',null,null,null,'Mary May','Casi','Bayog',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0019750','Staff',null,null,null,'Elsa','Icasupit','Bella',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044273','Staff',null,null,null,'Jocell','Concepcion','Belonio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0035928','Staff',null,null,null,'Bernard','Mangaoang','Berbano',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042339','Staff',null,null,null,'Charrie Mae','Gajwayen','Beyon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034904','Staff',null,null,null,'Rizalie','Sta Ana','Bobiles',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043305','Staff',null,null,null,'Angelica Myca','Suganob','Briones',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044275','Staff',null,null,null,'Emerson','Rabino','Bucsit',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042961','Staff',null,null,null,'Erika','Postrado','Buenaflor',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0000001','Staff',null,null,null,'Julian Jean','Serrato','Buenaventura',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040729','Staff',null,null,null,'Ema Lyka Mae','Soriano','Buenavista',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026158','Staff',null,null,null,'Eduardo','Orbe','Buizon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036513','Staff',null,null,null,'Mary Lou','Tudio','Bulfango',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044274','Staff',null,null,null,'Edielyn','Casuco','Burabo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033851','Staff',null,null,null,'Cristy','Flores','Busa',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038572','Staff',null,null,null,'Glyn','Depalobos','Bustamante',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043158','Staff',null,null,null,'Jessieliza','Braganaza','Cabanay',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026062','Staff',null,null,null,'Norman Kirby','Savlvaleon','Cabanding',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033010','Staff',null,null,null,'Rosalina','Gorembalem','Cahilig',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040727','Staff',null,null,null,'Riccel','Cagata','Callo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036507','Staff',null,null,null,'Rogil','Balinas','Calopez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044179','Staff',null,null,null,'Jsutine','Paglicawan','Calub',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041399','Staff',null,null,null,'Katherine Kaye','Rellesiva','Camaro',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042467','Staff',null,null,null,'Edison','Reoma','Campo','Jr',null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034790','Staff',null,null,null,'Rafael','Fernandez','Canales',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026225','Staff',null,null,null,'Prince Joushua','Francisco','Canapi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034791','Staff',null,null,null,'Mary Ann','Quintana','Cantonjos',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044180','Staff',null,null,null,'Allyssa Claire','Etulle','Capillo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041241','Staff',null,null,null,'Dwight Jorden','Reyes','Cardona',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039346','Staff',null,null,null,'Arlene','Escobar','Castillo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043307','Staff',null,null,null,'Josephine','Estonactoc','Castro',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036508','Staff',null,null,null,'Lyn','Cecillano','Castro',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0013991','Staff',null,null,null,'Shemmaey Pie','Dimalanta','Castro',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042772','Staff',null,null,null,'Daiana','Guiang','Cauilan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044276','Staff',null,null,null,'Angelica','Español','Cimanes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0029373','Staff',null,null,null,'Rosemarie','Roa','Clet',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043161','Staff',null,null,null,'Tesalonica Fresly','Bello','Corona',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034528','Staff',null,null,null,'Monica','Abendan','Correa',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031074','Staff',null,null,null,'Memie','Apolinario','Cortezano',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026239','Staff',null,null,null,'Alvie','Epogon','Cose',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042660','Staff',null,null,null,'Rhaymark','Cruz','Cruz',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042976','Staff',null,null,null,'Victoria','Labhata','Cruz',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042471','Staff',null,null,null,'Ace Spencer','Briol','Dante',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043308','Staff',null,null,null,'Franchette Iubileaum','Dela Paz','Dantoc',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042461','Staff',null,null,null,'Russelle','Luceño','Davasol',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042659','Staff',null,null,null,'Jannissa May','Chavez','De Chavez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043309','Staff',null,null,null,'Dexter','Asuncion','De Leon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042929','Staff',null,null,null,'Jamie','Espectacion','De Luna',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0016055','Staff',null,null,null,'Angelique','Nicolas','Dela Cerna',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0016850','Staff',null,null,null,'Rovelyn','Adarayan','Dela Cruz',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0032590','Staff',null,null,null,'Vilma','Caranzo','Dela Vega',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0025368','Staff',null,null,null,'Marie Daniel','Dela Cruz','Delos Santos',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043772','Staff',null,null,null,'Jerica','Cariaco','Depra',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037159','Staff',null,null,null,'John Jason','Medrano','Dionco',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040694','Staff',null,null,null,'Mary Joy',null,'Dizon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034831','Staff',null,null,null,'Norilyn','Antonio','Doctolero',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036159','Staff',null,null,null,'Airene','Acosta','Domingo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039651','Staff',null,null,null,'Justine','Pagaduan','Ebro',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041118','Staff',null,null,null,'Alyanna Jennifer','Pineda','Enriquez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0025685','Staff',null,null,null,'Cherygil','Rebucan','Enriquez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041233','Staff',null,null,null,'Cristina Joglen','Uribino','Equila',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042530','Staff',null,null,null,'Bell Daphne','Mercado','Escal',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036276','Staff',null,null,null,'Rachel','Olayres','Escolano',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0025794','Officer-In-Charge, Engineering Department',null,null,'ENGR','Cristopher','Poblete','Española',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040678','Staff',null,null,null,'Rowena','Watiwat','Estenor',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042466','Staff',null,null,null,'Hannaly','Cabasan','Eugenio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041394','Staff',null,null,null,'John Lester','Perez','Eupeña',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042930','Staff',null,null,null,'Florence Sofia','Miraña','Faurillo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036812','Staff',null,null,null,'Jessa','Beo','Faustino',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0014507','Staff',null,null,null,'Maria Christina','Delos Reyes','Fermo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026705','Staff',null,null,null,'John Benedict','Obillo','Fernando',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036509','Staff',null,null,null,'Jose Rolly','Verano','Flores',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0005495','Staff',null,null,null,'Richard','Valenzuela','Francisco',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040519','Staff',null,null,null,'Jerwine','Ignis','Fuentes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033854','Staff',null,null,null,'Ruhpa','Jaalun','Gabinul',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040241','Staff',null,null,null,'Lea','Galo','Gaffud',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0027127','Staff',null,null,null,'Daisy Marie','Abordaje','Gaje',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042995','Staff',null,null,null,'Gino','Moreno','Galus',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036809','Staff',null,null,null,'Nathaniel','Vargas','Galut',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043773','Staff',null,null,null,'Ann Gellene','Cardenas','Garcia',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043162','Staff',null,null,null,'Israel','Manalaysay','Geronimo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042884','Staff',null,null,null,'Maria Lourdes','Recomeo','Gonzales',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043955','Staff',null,null,null,'Allyssa Marie','Bince','Grande',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044277','Staff',null,null,null,'Joanna Grey','Cornelia','Graycochea',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043794','Staff',null,null,null,'Marie Leila Gwyneth','Bernardo','Gregorio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034450','Staff',null,null,null,'Hershey','Buison','Gresola',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037975','Staff',null,null,null,'Shiela Mae','Ausan','Hayan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036270','Staff',null,null,null,'Rovinz Saint','Espinosa','Hernandez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036502','Staff',null,null,null,'Jo-Anna Marie','Andayran','Hortillas',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041397','Staff',null,null,null,'Jibril Othman','Arpa','Ibno',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036601','Staff',null,null,null,'Joward','Callejas','Ibuyat',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042773','Staff',null,null,null,'Alliah Farrah','Cueno','Isnani',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043774','Staff',null,null,null,'Myra Belle','Blaza','Jan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036814','Staff',null,null,null,'Alex','Evangelista','Jimenez','Jr',null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040640','Staff',null,null,null,'Bernadeth','Ocon','Juanillo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031791','Staff',null,null,null,'Kimberly Beth Ponce','De Leon','Kampton',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040691','Staff',null,null,null,'Carlita','Ignacio','Labadan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034905','Staff',null,null,null,'Czarina','Belen','Labiana',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042977','Staff',null,null,null,'Pauline Kaye','Mata','Lagasca',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039348','Staff',null,null,null,'Nikko','Tacapan','Laurico',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038371','Staff',null,null,null,'Prechelle Ann','Sumaya','Lebios',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0032216','Staff',null,null,null,'Darrel','Paliza','Legaspi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0030180','Staff',null,null,null,'Jessica','Sala','Lepon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043310','Staff',null,null,null,'Hector','Tampo','Libay',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036606','Staff',null,null,null,'Jonalyn','San Jose','Ligon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044278','Staff',null,null,null,'Rica Mae','Catampongan','Lim',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040604','Staff',null,null,null,'Juvie','Natalio','Lindo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026227','Staff',null,null,null,'Jessica','Lequin','Lingcay',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041879','Staff',null,null,null,'Matthew Justin','Ho','Lirit',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041236','Staff',null,null,null,'Cathy Glen','Zuñiga','Lizada',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044521','Staff',null,null,null,'Jann Lauren','Salvador','Llasus',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040243','Staff',null,null,null,'Jhoan','Ybañez','Logico',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041798','Staff',null,null,null,'Margie','Molito','Lucañas',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036714','Staff',null,null,null,'Bernadette','Dy','Luna',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026069','Staff',null,null,null,'Jose Christoper','Vallecruz','Macario',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042184','Staff',null,null,null,'Janessah','Samsuden','Madale',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042462','Staff',null,null,null,'Antionette Dennel','Vinalay','Madrigal',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043311','Staff',null,null,null,'Trisha May',null,'Madrigal',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043641','Staff',null,null,null,'Ynnah',null,'Magallanes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040677','Staff',null,null,null,'Sophie Grace','Delariman','Magno',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042347','Staff',null,null,null,'Vince Japhet Arhon','Go','Mahilum',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044279','Staff',null,null,null,'Arriane','Catig','Malimata',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044280','Staff',null,null,null,'Kimberly','Perez','Mallari',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042887','Staff',null,null,null,'Norhamidah','Macarambon','Mamongcal',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034448','Staff',null,null,null,'Joel','Villanueva','Manalili',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042931','Staff',null,null,null,'Arnel','Lansangan','Marasigan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041398','Staff',null,null,null,'Rennavi','Robles','Medina',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044282','Staff',null,null,null,'Marvic','Protomarter','Meneses',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043638','Staff',null,null,null,'Maria Christine Isabelle','Ortiz','Menguis',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040689','Staff',null,null,null,'Preciosa','Sesuca','Mercado',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042458','Staff',null,null,null,'Abygail','Rebulanan','Mojica',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033332','Staff',null,null,null,'Glory Ann','Alarcon','Montes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036503','Staff',null,null,null,'Jan Rachel','Belches','Montes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031114','Staff',null,null,null,'Andy','Delfin','Montiague',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044181','Staff',null,null,null,'Mian','Gatab','Mores',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041803','Staff',null,null,null,'John Carl','Agullana','Nacional',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043770','Staff',null,null,null,'Joannah','Cerbito','Nadela',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0018646','Staff',null,null,null,'Jonajane','Candido','Narciso',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042348','Staff',null,null,null,'Kristine','Menciano','Nepomuceno',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042889','Staff',null,null,null,'Sanaira','Mamalatos','Nery',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041234','Staff',null,null,null,'Aileen Grace','Jumawan','Nimer',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040527','Staff',null,null,null,'Ma. Victoria','Jabasa','Norbe',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040747','Staff',null,null,null,'Melcy Joy','Morado','Oda',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037055','Staff',null,null,null,'Catherine','Baluyot','Oderon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037161','Staff',null,null,null,'Amabelle','Camartin','Oraye',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040686','Staff',null,null,null,'Irma','Caraiso','Oredina',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042657','Staff',null,null,null,'Skynard','Mercado','Orense',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033205','Staff',null,null,null,'Virgilio','Mercado','Orense','Iii',null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036713','Staff',null,null,null,'Marvin','Estrada','Orga','Jr',null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041117','Staff',null,null,null,'Princess','Allarey','Otico',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031787','Staff',null,null,null,'Ilyn','Crispino','Padua',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034069','Staff',null,null,null,'Mayla','Flores','Pagala',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041881','Staff',null,null,null,'Ferlyn','Priolo','Pamonag',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040237','Staff',null,null,null,'Renz','Rogan','Pascual',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042978','Staff',null,null,null,'Erica Mae','Quero','Passi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0032912','Staff',null,null,null,'Nelly Ann','Dagohoy','Pataueg',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041239','Staff',null,null,null,'Tharra','Grantos','Patiag',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039191','Staff',null,null,null,'Clilene','Cuenco','Perez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040245','Staff',null,null,null,'Erica Mae','Gono','Perez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034065','Staff',null,null,null,'John Wilson','Biglang-Awa','Perlawan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036712','Staff',null,null,null,'Kathleen Cris','Ragasa','Ponce',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040690','Staff',null,null,null,'Maria Diosvelina','Ignacio','Prisno',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0035031','Staff',null,null,null,'Christian',null,'Pulgo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026176','Staff',null,null,null,'Charlie Vic','Fuller','Puzon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042346','Staff',null,null,null,'Ephraim John','Caranto','Rafael',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042251','Staff',null,null,null,'Hazel Mae','Bonane','Rafuson',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040524','Staff',null,null,null,'Julie Ann','Nachor','Ramirez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036271','Staff',null,null,null,'Anthony','Abes','Ramos',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036512','Staff',null,null,null,'Jay','Carullo','Ramos','Jr',null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037042','Staff',null,null,null,'April Jessa','Leono','Rayala',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0007449','Staff',null,null,null,'Sheena','Barlin','Realengo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0023451','Staff',null,null,null,'Jade','Enitize','Reyes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036819','Staff',null,null,null,'Xyrish Jamaica','Anonat','Reyes',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042338','Staff',null,null,null,'Irman','Talon','Rinibatan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026113','Staff',null,null,null,'Claire Shyla','Vinluan','Rio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034832','Staff',null,null,null,'Ruevick Charles',null,'Rio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044558','Staff',null,null,null,'Khaila','Ocampo','Rivera',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0032638','Staff',null,null,null,'Berry Jade','Laxina','Rivo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042459','Staff',null,null,null,'Jan Mikole','Sarmiento','Rodriguez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044284','Staff',null,null,null,'Jonalyn','Hemino','Roja',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0031132','Staff',null,null,null,'Mary Jane','Paragas','Roldan',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041240','Staff',null,null,null,'Danica','Amascual','Roma',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034830','Staff',null,null,null,'Mickee','Pelayo','Roxas',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041232','Staff',null,null,null,'Gemma','Dennis','Sabino',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040239','Staff',null,null,null,'Edelina','Ballola','Sabulao',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040246','Staff',null,null,null,'Christine Joy','Dagalan','Saddi',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042344','Staff',null,null,null,'Fritz Nigel','Mabanta','Salem',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043160','Staff',null,null,null,'Jamaica','Salentes','Salidaga',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036717','Staff',null,null,null,'Jennielyn','Maravilla','Sallo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034524','Staff',null,null,null,'Exelsa','Nataño','Salo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044281','Staff',null,null,null,'Marjorie','De La Cruz','Salutin',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026151','Staff',null,null,null,'Ruel','Ruales','Samson',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042888','Staff',null,null,null,'Psalm','Azares','Sanchez',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040140','Staff',null,null,null,'Rumil','Bravo','Sangalang',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041390','Staff',null,null,null,'Mark',null,'Sanipa',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043163','Staff',null,null,null,'Christian Roque','Martinez','Sardeña',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042994','Staff',null,null,null,'Jeff Mon','Gaila','Satur',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044285','Staff',null,null,null,'Camill','Cecillano','Semana',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043312','Staff',null,null,null,'Natalie Kate','Gravador','Seva',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043313','Staff',null,null,null,'Marites','Wenceslao','Sidaya',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043795','Staff',null,null,null,'John Paolo',null,'Silvano',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0041880','Staff',null,null,null,'John','Altes','Solomon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034827','Staff',null,null,null,'Clarisse Anne','Juan','Sta Maria',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040679','Staff',null,null,null,'Hanica','Laycano','Sulion',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0042886','Staff',null,null,null,'Karen','Cabillo','Sulpico',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033333','Staff',null,null,null,'Vanessa','Montorio','Surmieda',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0028246','Staff',null,null,null,'Mark Joseph','Adarlo','Taba',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034792','Staff',null,null,null,'Ricky','Monteras','Tabing',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040231','Staff',null,null,null,'Natashia Kassandra','Granada','Tabios',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044286','Staff',null,null,null,'Divine','Macasil','Tabulao',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0033340','Staff',null,null,null,'Cywins','Amedo','Tamon',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043771','Staff',null,null,null,'Jessa Yvonne','Payomo','Tamondong',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0036155','Staff',null,null,null,'Jeffery','Ching','Timtiman',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034526','Staff',null,null,null,'Rosallee','Valle','Timtiman',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0039358','Staff',null,null,null,'Mary Joy','Dacanay','Tocus',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038089','Staff',null,null,null,'Virgilio','Peñaroyo','Tolentino',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040525','Staff',null,null,null,'Joshua','Mendoza','Torres',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0034449','Staff',null,null,null,'Rialyn','Taguiam','Trapani',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0011312','Staff',null,null,null,'Ramon',null,'Trinidad',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040141','Staff',null,null,null,'Kanleen Sonia','Kato','Udag',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044140','Staff',null,null,null,'Michelle Jean',null,'Vajio',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0040697','Staff',null,null,null,'Victor Deannielle','Baga','Valerozo',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0043159','Staff',null,null,null,'Loren','Aguilan','Villa',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0029884','Staff',null,null,null,'Myra Joy','Tamayo','Villa',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0044283','Staff',null,null,null,'Ranel','Aguilar','Villadolid',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026193','Staff',null,null,null,'Philippe','Yu','Wang',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0032633','Staff',null,null,null,'Mesael','Amine','Wingsing',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0038095','Staff',null,null,null,'Kaye Anne',null,'Yadao',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0026115','Staff',null,null,null,'Nancy','Columbres','Ydia',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
            ['CT-0037157','Staff',null,null,null,'Nicole Mae','Macasibang','Yu',null,null,null,'Contract Of Service','Active',null,'gray',1,1,null],
        ];

        foreach ($employees as $emp) {
            DB::table('employees')->updateOrInsert(
                ['employee_number' => $emp[0]],
                [
                    'employee_number' => $emp[0],
                    'role_position' => $emp[1],
                    'sg_level' => $emp[2],
                    'step_increment_id' => $emp[3],
                    'prefix' => $emp[4],
                    'first_name' => $emp[5],
                    'middle_name' => $emp[6],
                    'last_name' => $emp[7],
                    'suffix' => $emp[8],
                    'title' => $emp[9],
                    'position_designation' => $emp[10],
                    'employment_type' => $emp[11],
                    'employment_status' => $emp[12],
                    'avatar' => $emp[13],
                    'border_color' => $emp[14],
                    'aligned' => $emp[15],
                    'expanded' => $emp[16],
                    'notes' => $emp[17],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}