<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PlantillaItem;
use App\Models\SalaryGrade;

class PlantillaItemsSeeder extends Seeder
{
  public function run(): void
  {
    // ===========================
    // YOUR PLANTILLA LIST (DATA)
    // ===========================
    $rows = [
      ['department_id' => 29,    'division_id' =>  4,   'status' => 'FOR_PSB',             'item_no' => '1',      'sg' => 27, 'title' => 'CITY GOVERNMENT DEPARTMENT HEAD III'],
      ['department_id' => 29,    'division_id' =>  4,   'status' => 'FILLED',              'item_no' => '2',      'sg' => 26, 'title' => 'CITY GOVERNMENT DEPARTMENT HEAD II (MEDICAL CENTER CHIEF I)'],
      ['department_id' => 29,    'division_id' =>  4,   'status' => 'UNFILLED',            'item_no' => '3',      'sg' => 11, 'title' => 'COMPUTER MAINTENANCE TECHNOLOGIST I'],
      ['department_id' => 29,    'division_id' =>  4,   'status' => 'PENDING APPOINTMENT', 'item_no' => '4',      'sg' => 9,  'title' => 'ADMINISTRATIVE ASSISTANT III (SECRETARY II)'],
      ['department_id' => 23,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '5',      'sg' => 25, 'title' => 'MEDICAL SPECIALIST IV'],
      ['department_id' => 23,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '6',      'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '7',      'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '8-1',    'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '8-2',    'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '8-3',    'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '8-4',    'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '9',      'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '10',     'sg' => 15, 'title' => 'PSYCHOLOGIST II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '11',     'sg' => 14, 'title' => 'HEALTH EDUCATION AND PROMOTION OFFICER II'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '12-1',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '12-2',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '12-3',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '12-4',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 31,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '13',     'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '14',     'sg' => 11, 'title' => 'ADMINISTRATIVE OFFICER II (ADMINISTRATIVE OFFICER I)'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '15-1',   'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '15- 2',  'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '15-3',   'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '15-4',   'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' =>  2,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '15-5',   'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '16',     'sg' => 18, 'title' => 'NUTRITION-DIETITIAN III'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '17',     'sg' => 15, 'title' => 'NUTRITION-DIETITIAN II'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '18-1',   'sg' => 11, 'title' => 'NUTRITION-DIETITIAN I'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '18-2',   'sg' => 11, 'title' => 'NUTRITION-DIETITIAN I'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '19-1',   'sg' => 5,  'title' => 'COOK II'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '19-2',   'sg' => 5,  'title' => 'COOK II'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '19-3',   'sg' => 5,  'title' => 'COOK II'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '19-4',   'sg' => 5,  'title' => 'COOK II'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '20-1',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '20-2',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '20-3',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '20-4',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '21-1',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III (UTILITY WORKER II)'],
      ['department_id' => 26,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '21-2',   'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III (UTILITY WORKER II)'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '22',     'sg' => 18, 'title' => 'PHARMACIST III'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '23-1',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '23-2',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '23-3',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '23-4',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '23-5',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '23-6',   'sg' => 11, 'title' => 'PHARMACIST I'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '24',     'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV'],
      ['department_id' => 32,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '25',     'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III (UTILITY WORKER II)'],
      ['department_id' => 24,    'division_id' =>  1,   'status' => 'FOR_PSB',             'item_no' => '26',     'sg' => 18, 'title' => 'SOCIAL WELFARE OFFICER III'],
      ['department_id' => 24,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '27-1',   'sg' => 11, 'title' => 'SOCIAL WELFARE OFFICER I'],
      ['department_id' => 24,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '27-2',   'sg' => 11, 'title' => 'SOCIAL WELFARE OFFICER I'],
      ['department_id' => 24,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '27-3',   'sg' => 11, 'title' => 'SOCIAL WELFARE OFFICER I'],
      ['department_id' => 24,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '28',     'sg' => 8,  'title' => 'SOCIAL WELFARE ASSISTANT'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '29',     'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '30-1',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '30-2',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '31-1',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '31-2',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '31-3',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '31-4',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '31-5',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '31-6',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '32',     'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-4',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-5',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-6',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-7',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-8',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-9',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '33-10',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-1',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-2',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-3',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-4',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-5',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 15,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '34-6',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '35-1',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '35-2',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '35-3',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '35-4',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '35-5',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-1',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-2',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '36-3',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-4',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '36-5',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-6',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '36-7',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '36-8',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-9',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-10',  'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '36-11',  'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '36-12',  'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '37-1',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '37-2',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '37-3',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '37-4',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '37-5',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '37-6',   'sg' => 23, 'title' => 'MEDICAL OFFICER IV'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '38-1',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-2',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '38-3',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-4',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '38-5',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '38-6',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-7',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-8',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-9',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-10',  'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-11',  'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' =>  9,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '38-12',  'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '39-1',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '39-2',   'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '40-1',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '40-2',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '40-3',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 35,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '40-4',   'sg' => 21, 'title' => 'MEDICAL OFFICER III'],
      ['department_id' => 13,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '41',     'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 13,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '42',     'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '43',     'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '44',     'sg' => 18, 'title' => 'MEDICAL TECHNOLOGIST III'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '45-1',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '45-2',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '45-3',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '46-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '46-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' =>  5,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '46-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '47',     'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '48',     'sg' => 18, 'title' => 'MEDICAL TECHNOLOGIST III'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '49-1',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '49-2',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '49-3',   'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '50',     'sg' => 15, 'title' => 'CHEMIST II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '51-1',   'sg' => 11, 'title' => 'MEDICAL TECHNOLOGIST I'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '51-2',   'sg' => 11, 'title' => 'MEDICAL TECHNOLOGIST I'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '51-3',   'sg' => 11, 'title' => 'MEDICAL TECHNOLOGIST I'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '51-4',   'sg' => 11, 'title' => 'MEDICAL TECHNOLOGIST I'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '52-1',   'sg' => 8,  'title' => 'MEDICAL LABORATORY TECHNICIAN II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '52-2',   'sg' => 8,  'title' => 'MEDICAL LABORATORY TECHNICIAN II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '52-3',   'sg' => 8,  'title' => 'MEDICAL LABORATORY TECHNICIAN II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '52-4',   'sg' => 8,  'title' => 'MEDICAL LABORATORY TECHNICIAN II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '53-1',   'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '53-2',   'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '53-3',   'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' =>  3,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '53-4',   'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '54',     'sg' => 24, 'title' => 'MEDICAL SPECIALIST III'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '55-1',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '55-2',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '56',     'sg' => 18, 'title' => 'RADIOLOGIC TECHNOLOGIST III'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '57-1',   'sg' => 15, 'title' => 'RADIOLOGIC TECHNOLOGIST II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '57-2',   'sg' => 15, 'title' => 'RADIOLOGIC TECHNOLOGIST II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '57-3',   'sg' => 15, 'title' => 'RADIOLOGIC TECHNOLOGIST II'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '58-1',   'sg' => 11, 'title' => 'RADIOLOGIC TECHNOLOGIST I'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '58-2',   'sg' => 11, 'title' => 'RADIOLOGIC TECHNOLOGIST I'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '58-3',   'sg' => 11, 'title' => 'RADIOLOGIC TECHNOLOGIST I'],
      ['department_id' => 14,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '59',     'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (CLERK II)'],
      ['department_id' => 12,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '60',     'sg' => 23, 'title' => 'DENTIST IV'],
      ['department_id' => 12,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '61',     'sg' => 17, 'title' => 'DENTIST II'],
      ['department_id' => 12,    'division_id' =>  1,   'status' => 'FILLED',              'item_no' => '62',     'sg' => 4,  'title' => 'DENTAL AIDE'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '63',     'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (INFORMATION OFFICER III)'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '64',     'sg' => 15, 'title' => 'STATISTICIAN II'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'PENDING APPOINTMENT', 'item_no' => '65',     'sg' => 15, 'title' => 'ADMINISTRATIVE OFFICER IV (INFORMATION OFFICER II)'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'IMPENDING',           'item_no' => '66',     'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '67',     'sg' => 11, 'title' => 'ADMINISTRATIVE OFFICER II (INFORMATION OFFICER I)'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '68-1',   'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (DATA CONTROLLER II)'],
      ['department_id' => 17,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '68-2',   'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (DATA CONTROLLER II)'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '69-1',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II (PART-TIME)'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '69-2',   'sg' => 23, 'title' => 'MEDICAL SPECIALIST II (PART-TIME)'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '70-1',   'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '70-2',   'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '71',     'sg' => 15, 'title' => 'MEDICAL TECHNOLOGIST II'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '72',     'sg' => 11, 'title' => 'MIDWIFE II'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '73',     'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '74',     'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (DRIVER II)'],
      ['department_id' => 19,    'division_id' =>  1,   'status' => 'UNFILLED',            'item_no' => '75',     'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III (UTILITY WORKER II)'],
      ['department_id' => 28,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '76',     'sg' => 22, 'title' => 'NURSE VI'],
      ['department_id' => 28,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '77',     'sg' => 20, 'title' => 'NURSE V'],
      ['department_id' => 28,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '78',     'sg' => 19, 'title' => 'NURSE IV'],
      ['department_id' => 28,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '79',     'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '80-1',   'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '80-2',   'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '81-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '81-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '81-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '81-4',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-1',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'IMPENDING',           'item_no' => '82-2',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-3',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-4',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-5',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-6',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-7',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-8',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-9',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-10',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-11',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-12',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-13',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-14',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-15',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-16',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-17',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-18',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-19',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-20',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-21',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-22',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-23',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-24',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-25',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-26',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-27',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-28',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-29',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-30',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-31',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-32',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-33',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-34',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-35',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-36',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-37',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-38',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-39',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-40',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-41',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-42',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-43',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-44',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-45',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-46',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-47',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-48',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '82-49',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-50',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '82-51',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-1',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-2',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '83-3',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-4',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-5',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-6',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '83-7',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-8',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-9',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-10',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-11',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-12',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-13',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '83-14',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-15',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-16',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-17',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-18',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-19',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-20',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-21',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-22',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-23',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-24',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '83-25',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 10,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '83-26',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '84',     'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '85-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '85-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '86-1',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '86-2',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '86-3',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '86-4',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-5',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-6',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-7',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-8',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-9',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-10',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-11',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '86-12',  'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '87-1',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '87-2',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-1',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-2',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-3',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-4',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-5',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 30,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '88-6',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '89',     'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '90-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '90-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '90-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '90-4',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '90-5',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '90-6',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '91-1',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '91-2',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '91-3',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '91-4',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '91-5',   'sg' => 15, 'title' => 'NURSE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '92-1',   'sg' => 9,  'title' => 'MIDWIFE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '92-2',   'sg' => 9,  'title' => 'MIDWIFE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '92-3',   'sg' => 9,  'title' => 'MIDWIFE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '92-4',   'sg' => 9,  'title' => 'MIDWIFE I'],
      ['department_id' => 11,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '92-5',   'sg' => 9,  'title' => 'MIDWIFE I'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '93',     'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '94-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '94-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '94-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '94-4',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '94-5',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '94-6',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '95-1',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '95-2',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '96-1',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '96-2',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 36,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '96-3',   'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '97',     'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '98-1',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '98-2',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '98-3',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '98-4',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '98-5',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '98-6',   'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '99-1',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '99-2',   'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 21,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '100',    'sg' => 17, 'title' => 'NURSE III'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '101-1',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-2',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-3',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-4',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-5',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-6',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-7',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-8',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-9',  'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-10', 'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-11', 'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-12', 'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-13', 'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '101-14', 'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '102-1',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '102-2',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '102-3',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '102-4',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '102-5',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 25,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '102-6',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '103',    'sg' => 14, 'title' => 'RESPIRATORY THERAPIST II'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '104-1',  'sg' => 10, 'title' => 'RESPIRATORY THERAPIST I'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '104-2',  'sg' => 10, 'title' => 'RESPIRATORY THERAPIST I'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '104-3',  'sg' => 10, 'title' => 'RESPIRATORY THERAPIST I'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '105-1',  'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '105-2',  'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' => 34,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '105-3',  'sg' => 4,  'title' => 'LABORATORY AIDE II'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '106',    'sg' => 16, 'title' => 'NURSE II'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '107-1',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '107-2',  'sg' => 6,  'title' => 'NURSING ATTENDANT II'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '108-1',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'FILLED',              'item_no' => '108-2',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '108-3',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '108-4',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' =>  8,    'division_id' =>  3,   'status' => 'UNFILLED',            'item_no' => '108-5',  'sg' => 4,  'title' => 'NURSING ATTENDANT I'],
      ['department_id' => 27,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '109',    'sg' => 24, 'title' => 'CHIEF ADMINISTRATIVE OFFICER (ADMINISTRATIVE OFFICER V)'],
      ['department_id' => 27,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '110',    'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I'],
      ['department_id' => 27,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '111',    'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '112',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (HUMAN RESOURCE MANAGEMENT OFFICER III)'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'PENDING APPOINTMENT', 'item_no' => '113',    'sg' => 15, 'title' => 'ADMINISTRATIVE OFFICER IV (HUMAN RESOURCE MANAGEMENT OFFICER II)'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '114',    'sg' => 14, 'title' => 'ADMINISTRATIVE OFFICER III'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '115',    'sg' => 11, 'title' => 'ADMINISTRATIVE OFFICER II (HUMAN RESOURCE MANAGEMENT OFFICER I)'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '116-1',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (HUMAN RESOURCE MANAGEMENT ASSISTANT I)'],
      ['department_id' => 20,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '116-2',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (HUMAN RESOURCE MANAGEMENT ASSISTANT I)'],
      ['department_id' => 33,    'division_id' =>  2,   'status' => 'PENDING APPOINTMENT', 'item_no' => '117',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (SUPPLY OFFICER III)'],
      ['department_id' => 33,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '118',    'sg' => 14, 'title' => 'ADMINISTRATIVE OFFICER III (SUPPLY OFFICER II)'],
      ['department_id' => 33,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '119',    'sg' => 9,  'title' => 'ADMINISTRATIVE ASSISTANT III (BUYER III)'],
      ['department_id' => 33,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '120-1',  'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' => 33,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '120-2',  'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' =>  6,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '121',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (BUDGET OFFICER III)'],
      ['department_id' =>  6,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '122',    'sg' => 15, 'title' => 'ADMINISTRATIVE OFFICER IV (BUDGET OFFICER II)'],
      ['department_id' =>  6,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '123',    'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (BUDGETING ASSISTANT)'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '124',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (SUPPLY OFFICER III)'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'PENDING APPOINTMENT', 'item_no' => '125',    'sg' => 8,  'title' => 'WAREHOUSEMAN II'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '126',    'sg' => 7,  'title' => 'ADMINISTRATIVE ASSISTANT I (COMPUTER OPERATOR I)'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '127-1',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (STOREKEEPER I)'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '127-2',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (STOREKEEPER I)'],
      ['department_id' => 22,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '127-3',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (STOREKEEPER I)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '128',    'sg' => 19, 'title' => 'ENGINEER III'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '129',    'sg' => 16, 'title' => 'ENGINEER II'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '130-1',  'sg' => 11, 'title' => 'MEDICAL EQUIPMENT TECHNICIAN III'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '130-2',  'sg' => 11, 'title' => 'MEDICAL EQUIPMENT TECHNICIAN III'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '131',    'sg' => 8,  'title' => 'MEDICAL EQUIPMENT TECHNICIAN II'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '132-1',  'sg' => 6,  'title' => 'MEDICAL EQUIPMENT TECHNICIAN I'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '132-2',  'sg' => 6,  'title' => 'MEDICAL EQUIPMENT TECHNICIAN I'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '133-1',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (ELECTRICIAN II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '133-2',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (ELECTRICIAN II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '134',    'sg' => 5,  'title' => 'ADMINISTRATIVE AIDE V (PLUMBER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '135',    'sg' => 5,  'title' => 'ADMINISTRATIVE AIDE V (CARPENTER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '136-1',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (DRIVER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '136-2',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (DRIVER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '136-3',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (DRIVER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '136-4',  'sg' => 4,  'title' => 'ADMINISTRATIVE AIDE IV (DRIVER II)'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '137-1',  'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '137-2',  'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 16,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '137-3',  'sg' => 3,  'title' => 'ADMINISTRATIVE AIDE III'],
      ['department_id' => 18,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '138-1',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (UTILITY FOREMAN)'],
      ['department_id' => 18,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '138-2',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (UTILITY FOREMAN)'],
      ['department_id' => 18,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '139-1',  'sg' => 3,  'title' => 'LAUNDRY WORKER II'],
      ['department_id' => 18,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '139-2',  'sg' => 3,  'title' => 'LAUNDRY WORKER II'],
      ['department_id' => 18,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '140',    'sg' => 2,  'title' => 'SEAMSTRESS'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'FOR_PSB',             'item_no' => '141',    'sg' => 19, 'title' => 'ACCOUNTANT III'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '142',    'sg' => 16, 'title' => 'ACCOUNTANT II'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'IMPENDING',           'item_no' => '143-1',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (ACCOUNTING CLERK III)'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '143-2',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (ACCOUNTING CLERK III)'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '143-3',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (ACCOUNTING CLERK III)'],
      ['department_id' =>  1,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '143-4',  'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (ACCOUNTING CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'PENDING APPOINTMENT', 'item_no' => '144',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (ADMINISTRATIVE OFFICER III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '145',    'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (ACCOUNTING CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '146-1',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '146-2',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '146-3',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '146-4',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  4,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '146-5',  'sg' => 6,  'title' => 'ADMINISTRATIVE AIDE VI (CLERK III)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'PENDING APPOINTMENT', 'item_no' => '147',    'sg' => 18, 'title' => 'ADMINISTRATIVE OFFICER V (CASHIER III)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '148-1',  'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I (CASHIER I)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'FILLED',              'item_no' => '148-2',  'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I (CASHIER I)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '148-3',  'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I (CASHIER I)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '148-4',  'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I (CASHIER I)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '148-5',  'sg' => 10, 'title' => 'ADMINISTRATIVE OFFICER I (CASHIER I)'],
      ['department_id' =>  7,    'division_id' =>  2,   'status' => 'UNFILLED',            'item_no' => '149',    'sg' => 8,  'title' => 'ADMINISTRATIVE ASSISTANT II (CASH CLERK III)'],
    ];
       foreach ($rows as $r) {

            // ✅ Normalize status (handles "PENDING APPOINTMENT" etc.)
            $status = strtoupper(str_replace(' ', '_', trim($r['status'])));

            // ✅ Find salary grade id
            $sg = SalaryGrade::where('salary_grade', $r['sg'])->first();

            if (!$sg) {
                // if wala pang salary grade seed, skip or create
                $sg = SalaryGrade::create([
                    'salary_grade' => $r['sg'],
                    'monthly_salary' => null,
                    'annual_salary' => null,
                ]);
            }

            PlantillaItem::updateOrCreate(
                ['item_number' => $r['item_no']], // ✅ unique key
                [
                    'department_id' => $r['department_id'],
                    'division_id' => $r['division_id'],
                    'status' => $status,            // ✅ enum value
                    'salary_grade_id' => $sg->id,   // ✅ required FKs
                    'title' => $r['title'],
                    'description' => $r['description'] ?? null,
                ]
            );
        }
    }
}